import { Recipe } from '../models/Recipe';

export const DEMO_RECIPES: Recipe[] = [
  {
    id: 'demo-spaghetti-bolognese',
    name: 'Spaghetti Bolognese',
    servings: '4',
    prepTime: '15 min',
    cookTime: '45 min',
    categories: ['Dinner', 'Italian', 'Pasta'],
    imageUrl: 'https://images.unsplash.com/photo-1622973536968-3ead9e780960?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    userId: 'demo-user',
    visibility: 'public',
    ingredients: [
      { amount: '1', unit: 'lb', item: 'ground beef', id: 'ing-1' },
      { amount: '1', unit: '', item: 'onion, diced', id: 'ing-2' },
      { amount: '3', unit: 'cloves', item: 'garlic, minced', id: 'ing-3' },
      { amount: '1', unit: 'can (28 oz)', item: 'crushed tomatoes', id: 'ing-4' },
      { amount: '2', unit: 'tbsp', item: 'tomato paste', id: 'ing-5' },
      { amount: '1', unit: 'tsp', item: 'dried oregano', id: 'ing-6' },
      { amount: '1', unit: 'tsp', item: 'dried basil', id: 'ing-7' },
      { amount: '1', unit: 'lb', item: 'spaghetti', id: 'ing-8' },
      { amount: '', unit: '', item: 'salt and pepper to taste', id: 'ing-9' },
      { amount: '', unit: '', item: 'parmesan cheese for serving', id: 'ing-10' },
    ],
    instructions: [
      { text: 'Bring a large pot of salted water to a boil for the pasta.', id: 'ins-1' },
      { text: 'In a large skillet, brown the ground beef over medium-high heat, breaking it into small pieces. Drain excess fat.', id: 'ins-2' },
      { text: 'Add the diced onion and cook until softened, about 5 minutes. Add the garlic and cook for 1 minute more.', id: 'ins-3' },
      { text: 'Stir in the crushed tomatoes, tomato paste, oregano, and basil. Season with salt and pepper.', id: 'ins-4' },
      { text: 'Reduce heat to low and simmer for 30 minutes, stirring occasionally.', id: 'ins-5' },
      { text: 'Cook spaghetti according to package directions. Drain and serve topped with the sauce and parmesan cheese.', id: 'ins-6' },
    ],
  },
  {
    id: 'demo-blueberry-pancakes',
    name: 'Blueberry Pancakes',
    servings: '4',
    prepTime: '10 min',
    cookTime: '15 min',
    categories: ['Breakfast', 'American'],
    imageUrl: 'https://images.unsplash.com/photo-1528198622811-0842b4e50787?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    userId: 'demo-user',
    visibility: 'public',
    ingredients: [
      { amount: '1.5', unit: 'cups', item: 'all-purpose flour', id: 'ing-11' },
      { amount: '2', unit: 'tbsp', item: 'sugar', id: 'ing-12' },
      { amount: '2', unit: 'tsp', item: 'baking powder', id: 'ing-13' },
      { amount: '0.5', unit: 'tsp', item: 'salt', id: 'ing-14' },
      { amount: '1', unit: 'cup', item: 'milk', id: 'ing-15' },
      { amount: '1', unit: '', item: 'egg', id: 'ing-16' },
      { amount: '3', unit: 'tbsp', item: 'melted butter', id: 'ing-17' },
      { amount: '1', unit: 'cup', item: 'fresh blueberries', id: 'ing-18' },
      { amount: '', unit: '', item: 'maple syrup for serving', id: 'ing-19' },
    ],
    instructions: [
      { text: 'In a large bowl, whisk together the flour, sugar, baking powder, and salt.', id: 'ins-7' },
      { text: 'In a separate bowl, whisk together the milk, egg, and melted butter.', id: 'ins-8' },
      { text: 'Pour the wet ingredients into the dry ingredients and stir until just combined. Do not overmix — a few lumps are fine.', id: 'ins-9' },
      { text: 'Gently fold in the blueberries.', id: 'ins-10' },
      { text: 'Heat a non-stick skillet or griddle over medium heat and lightly grease with butter.', id: 'ins-11' },
      { text: 'Pour about 1/4 cup of batter per pancake. Cook until bubbles form on the surface, then flip and cook until golden brown.', id: 'ins-12' },
      { text: 'Serve warm with maple syrup and extra blueberries.', id: 'ins-13' },
    ],
  },
  {
    id: 'demo-chocolate-chip-cookies',
    name: 'Chocolate Chip Cookies',
    servings: '24 cookies',
    prepTime: '15 min',
    cookTime: '12 min',
    categories: ['Dessert', 'Baking', 'American'],
    imageUrl: 'https://images.unsplash.com/photo-1747494750619-e599070ee148?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    userId: 'demo-user',
    visibility: 'public',
    ingredients: [
      { amount: '2.25', unit: 'cups', item: 'all-purpose flour', id: 'ing-20' },
      { amount: '1', unit: 'tsp', item: 'baking soda', id: 'ing-21' },
      { amount: '1', unit: 'tsp', item: 'salt', id: 'ing-22' },
      { amount: '1', unit: 'cup', item: 'butter, softened', id: 'ing-23' },
      { amount: '0.75', unit: 'cup', item: 'granulated sugar', id: 'ing-24' },
      { amount: '0.75', unit: 'cup', item: 'packed brown sugar', id: 'ing-25' },
      { amount: '2', unit: '', item: 'large eggs', id: 'ing-26' },
      { amount: '2', unit: 'tsp', item: 'vanilla extract', id: 'ing-27' },
      { amount: '2', unit: 'cups', item: 'semi-sweet chocolate chips', id: 'ing-28' },
    ],
    instructions: [
      { text: 'Preheat oven to 375°F (190°C). Line baking sheets with parchment paper.', id: 'ins-14' },
      { text: 'In a medium bowl, whisk together the flour, baking soda, and salt. Set aside.', id: 'ins-15' },
      { text: 'In a large bowl, cream together the softened butter, granulated sugar, and brown sugar until light and fluffy.', id: 'ins-16' },
      { text: 'Beat in the eggs one at a time, then stir in the vanilla extract.', id: 'ins-17' },
      { text: 'Gradually blend in the flour mixture until just combined. Fold in the chocolate chips.', id: 'ins-18' },
      { text: 'Drop rounded tablespoons of dough onto the prepared baking sheets, spacing them about 2 inches apart.', id: 'ins-19' },
      { text: 'Bake for 10-12 minutes or until edges are golden brown. Let cool on the baking sheet for 5 minutes before transferring to a wire rack.', id: 'ins-20' },
    ],
  },
  {
    id: 'demo-mediterranean-salad',
    name: 'Mediterranean Salad',
    servings: '2',
    prepTime: '15 min',
    cookTime: '0 min',
    categories: ['Lunch', 'Salad', 'Mediterranean', 'Healthy'],
    imageUrl: 'https://images.unsplash.com/photo-1722032617357-7b09276b1a8d?q=80&w=1173&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    userId: 'demo-user',
    visibility: 'public',
    ingredients: [
      { amount: '4', unit: 'cups', item: 'mixed greens', id: 'ing-29' },
      { amount: '1', unit: 'cup', item: 'cherry tomatoes, halved', id: 'ing-30' },
      { amount: '1', unit: '', item: 'cucumber, diced', id: 'ing-31' },
      { amount: '0.5', unit: 'cup', item: 'kalamata olives', id: 'ing-32' },
      { amount: '0.5', unit: 'cup', item: 'crumbled feta cheese', id: 'ing-33' },
      { amount: '0.25', unit: 'cup', item: 'red onion, thinly sliced', id: 'ing-34' },
      { amount: '3', unit: 'tbsp', item: 'extra virgin olive oil', id: 'ing-35' },
      { amount: '1', unit: 'tbsp', item: 'red wine vinegar', id: 'ing-36' },
      { amount: '1', unit: 'tsp', item: 'dried oregano', id: 'ing-37' },
      { amount: '', unit: '', item: 'salt and pepper to taste', id: 'ing-38' },
    ],
    instructions: [
      { text: 'Arrange the mixed greens on a large plate or in a bowl.', id: 'ins-21' },
      { text: 'Top with the cherry tomatoes, cucumber, kalamata olives, feta cheese, and red onion.', id: 'ins-22' },
      { text: 'In a small bowl, whisk together the olive oil, red wine vinegar, and dried oregano. Season with salt and pepper.', id: 'ins-23' },
      { text: 'Drizzle the dressing over the salad and toss gently to combine. Serve immediately.', id: 'ins-24' },
    ],
  },
];

export function getDemoRecipeBySlug(slug: string): Recipe | undefined {
  return DEMO_RECIPES.find((recipe) => recipe.id === slug);
}

export function isDemoRecipeSlug(slug: string): boolean {
  return slug.startsWith('demo-');
}
